#! /usr/bin/env sh
#
# Butler
#
# A task runner to simplify development
# Let the Butler do it.

if [[ "$OSTYPE" == *darwin* ]]; then
  READLINK_CMD='greadlink'
else
  READLINK_CMD='readlink'
fi

dot="$(cd "$(dirname "$([ -L "$0" ] && $READLINK_CMD -f "$0" || echo "$0")")"; pwd)"

source "$dot/butler-base.sh"

butler "$@"
